baseURL = 'https://dandeilit.github.io/'
languageCode = 'zh-cn'
title = 'dandeilit’s blog'
theme = 'PaperMod'

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[menus]
[[menus.main]]
name = 'Archive'
pageRef = '/archives'
weight = 5
[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 10
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 10

[params]
homeInfoParams = { Title = '信言不美，美言不信' }
socialIcons = [
    { name = 'github', url = 'https://github.com/dandeilit' },
    { name = 'roadmap', url = 'https://roadmap.sh/aspnet-core?s=6570be3a5145316d25c8bc59' },
]
ShowToc = true
ShowBreadCrumbs = false
# [params.editPost]
# URL = "https://github.com/<path_to_repo>/content"
# Text = "Suggest Changes" # edit text
# appendFilePath = true # to append file path to Edit link
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[outputs]
home = ['HTML', 'RSS', 'JSON']
